name: Fuligo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running ` pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.21  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  cupertino_icons: ^1.0.2
  flushbar: ^1.10.4
  http: ^0.13.4
  shared_preferences: ^2.0.12
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  top_snackbar_flutter: ^1.0.2
  another_flushbar: ^1.10.28
  flutter_spinkit: ^5.1.0
  loading_indicator: ^3.0.2
  flutter_smart_dialog: ^3.3.7
  firebase_database: ^9.0.11
  provider: ^6.0.2
  cloud_firestore: ^3.1.10
  file_picker: ^1.10.0
  firebase_storage: ^10.2.10
 
  image_picker: ^0.6.5+3
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.8
  email_validator: ^2.0.1
  flutter_dialogs: ^2.1.1
  video_player: ^2.1.10
  flutter_map: ^0.14.0
  latlong: ^0.6.1
  # audioplayers: ^0.20.1
  audio_video_progress_bar: ^0.10.0
  rxdart: ^0.27.3
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  accordion: ^2.2.1
  mapbox_api: ^1.0.0
  polyline: ^1.0.2
  flutter_fadein: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_blurhash: ^0.6.4
  transparent_image: ^2.0.0
  page_transition: ^2.0.5
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter_compass: ^0.7.0
  # location: ^4.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_launcher_icons: ^0.9.2
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
  
#   image_path: " assets/images/logo.png"  


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/font/
    - assets/images/location_marker.png
    
    - assets/images/logo.png
    - assets/images/explore.png
  
    - assets/images/discover.png
    
    - assets/images/png/icon-umbrella.png
   
    - assets/images/menu/icon-map.png  
    - assets/images/menu/icon-chat.png  
    - assets/images/menu/icon-settings.png  
    - assets/images/menu/icon-documents.png  
    - assets/images/menu/icon-gamification.png  
    - assets/images/menu/icon-menu.png  
  
    - assets/images/button-play.png
    - assets/images/icon-tooltip.png
    - assets/images/icon-compass.png
    - assets/images/compass-needle.png
    - assets/images/compass-rose.png
    - assets/images/direction_close.png
   
    - assets/images/icon-achievement.png
    - assets/images/icon-booking.png
    - assets/images/icon-close.png
    - assets/images/icon-route.png
    - assets/images/icon-medal.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: fuligofont
      fonts:
        - asset: assets/font/fontello.ttf
         
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
    # - family: Trajan Pro
      # fonts:
      #   - asset: fonts/TrajanPro.ttf
      #   - asset: fonts/TrajanPro_Bold.ttf
      #     weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages